<?php
$gamePageMeta = [
  'last_updated' => 'April 10, 2026',
  'coverage_month' => 'April 2026',
  'editor_note' => 'New this month: the card art is fully refreshed, Disco Elysium and Chants of Sennaar joined the visual lineup, and Pokemon TCG Pocket is still the fastest recommendation for casual tablet play.',
  'refresh_rhythm' => 'Refresh one or two picks every month, rotate the featured slot when a stronger title lands, and keep routing readers toward the best-fit tablet category.',
  'monthly_focus' => 'Best tablet games to play this month on iPad, Android tablets, and Surface devices.',
];

$games = [
  [
    'name' => 'Pokemon TCG Pocket',
    'img' => 'assets/images/games/pokemon-tcg-pocket.png',
    'img_fit' => 'contain',
    'genre' => 'Card Strategy',
    'badge' => 'Best Overall Pick',
    'featured' => true,
    'new_this_month' => true,
    'published_month' => '2026-04',
    'platforms' => ['iPad', 'Android Tablet'],
    'best_tablet' => 'iPad Air or Galaxy Tab S9 FE',
    'fit' => 'Fast sessions, clean touch controls, and a card layout that scales well on larger displays.',
    'best_for' => 'Players who want collectible strategy, quick matches, and a game that feels natural in portrait or landscape.',
    'source_label' => 'Google Play Best Game 2025',
    'source_url' => 'https://blog.google/products/google-play/best-apps-games-2025/',
    'shop_href' => 'shop.php?brand=Apple',
    'tablet_brand' => 'Apple',
    'cta_label' => 'Shop Apple Picks',
    'review_href' => 'reviews.php',
    'comparison_note' => 'If you want the least-friction pick for daily tablet use, start here and then compare compact iPad and Galaxy Tab options.',
  ],
  [
    'name' => 'DREDGE',
    'img' => 'assets/images/games/dredge.png',
    'img_fit' => 'cover',
    'genre' => 'Atmospheric Adventure',
    'badge' => 'Premium Favorite',
    'featured' => false,
    'new_this_month' => false,
    'published_month' => '2026-03',
    'platforms' => ['iPad', 'Android Tablet'],
    'best_tablet' => 'iPad Pro or iPad Air',
    'fit' => 'A slow-burn premium game that benefits from a bigger display, dark-room visuals, and touch-first inventory play.',
    'best_for' => 'Players who want a richer single-player experience instead of another free-to-play loop.',
    'source_label' => 'Apple iPad Game of the Year 2025 and Google Play Best on Play Pass 2025',
    'source_url' => 'https://developer.apple.com/app-store/app-store-awards-2025/',
    'shop_href' => 'shop.php?brand=Apple',
    'tablet_brand' => 'Apple',
    'cta_label' => 'Shop Premium iPads',
    'review_href' => 'reviews.php',
    'comparison_note' => 'Best for buyers who want a stronger display and enough overhead for slower, mood-driven premium games.',
  ],
  [
    'name' => 'Infinity Nikki',
    'img' => 'assets/images/games/infinity-nikki.png',
    'img_fit' => 'cover',
    'genre' => 'Open-World Adventure',
    'badge' => 'Apple Finalist',
    'featured' => false,
    'new_this_month' => true,
    'published_month' => '2026-04',
    'platforms' => ['iPad'],
    'best_tablet' => 'iPad Pro',
    'fit' => 'Large environments, outfit-driven progression, and bright visual design make more sense on a large tablet than on a phone.',
    'best_for' => 'Players who want exploration, collecting, and a polished visual experience.',
    'source_label' => 'Apple App Store Awards 2025 iPad finalist',
    'source_url' => 'https://apps.apple.com/ga/app/infinity-nikki/id6502622570',
    'shop_href' => 'shop.php?brand=Apple',
    'tablet_brand' => 'Apple',
    'cta_label' => 'Shop High-End iPads',
    'review_href' => 'reviews.php',
    'comparison_note' => 'A visual showcase pick for shoppers deciding whether a premium iPad display is worth it.',
  ],
  [
    'name' => 'Prince of Persia Lost Crown',
    'img' => 'assets/images/games/prince-of-persia-lost-crown.png',
    'img_fit' => 'cover',
    'genre' => 'Action Platformer',
    'badge' => 'Apple Finalist',
    'featured' => false,
    'new_this_month' => false,
    'published_month' => '2026-03',
    'platforms' => ['iPad'],
    'best_tablet' => 'iPad Air or iPad Pro',
    'fit' => 'Precision combat and platforming benefit from the extra screen space and premium performance headroom.',
    'best_for' => 'Players who want something sharper and faster than a casual mobile platformer.',
    'source_label' => 'Apple App Store Awards 2025 iPad finalist',
    'source_url' => 'https://developer.apple.com/app-store/app-store-awards-2025/',
    'shop_href' => 'shop.php?brand=Apple',
    'tablet_brand' => 'Apple',
    'cta_label' => 'Compare iPad Performance',
    'review_href' => 'reviews.php',
    'comparison_note' => 'A strong benchmark game for shoppers deciding between the iPad Air and iPad Pro tier.',
  ],
  [
    'name' => 'Disney Speedstorm',
    'img' => 'assets/images/games/disney-speedstorm.png',
    'img_fit' => 'cover',
    'genre' => 'Arcade Racing',
    'badge' => 'Best Multi-Device',
    'featured' => false,
    'new_this_month' => false,
    'published_month' => '2026-03',
    'platforms' => ['Android Tablet', 'Surface'],
    'best_tablet' => 'Galaxy Tab S10 or Surface Pro 11',
    'fit' => 'Google specifically recognized it for strong play across PC, tablet, and mobile, which is exactly the story this page should tell.',
    'best_for' => 'Players who want fast races, local pickup-and-play energy, and a game that travels well across screens.',
    'source_label' => 'Google Play Best Multi-device Game 2025',
    'source_url' => 'https://blog.google/products/google-play/best-apps-games-2025/',
    'shop_href' => 'shop.php?brand=Samsung',
    'tablet_brand' => 'Samsung',
    'cta_label' => 'Shop Multi-Device Tablets',
    'review_href' => 'reviews.php',
    'comparison_note' => 'A useful commerce bridge for users choosing between a Galaxy Tab and a work-and-play Surface.',
  ],
  [
    'name' => 'Disco Elysium',
    'img' => 'assets/images/games/disco-elysium.png',
    'img_fit' => 'cover',
    'genre' => 'Story RPG',
    'badge' => 'Best Story',
    'featured' => false,
    'new_this_month' => true,
    'published_month' => '2026-04',
    'platforms' => ['Android Tablet', 'Surface'],
    'best_tablet' => 'Surface Pro or Galaxy Tab S10 Ultra',
    'fit' => 'Dense reading, choice-heavy storytelling, and slower pacing are much more comfortable on a tablet than on a smaller phone display.',
    'best_for' => 'Players who want narrative depth, not twitch gameplay.',
    'source_label' => 'Google Play Best Story 2025',
    'source_url' => 'https://blog.google/products/google-play/best-apps-games-2025/',
    'shop_href' => 'shop.php?brand=Microsoft',
    'tablet_brand' => 'Microsoft',
    'cta_label' => 'Shop Surface Picks',
    'review_href' => 'reviews.php',
    'comparison_note' => 'Ideal for readers comparing larger-screen tablets for text-heavy, slower games and productivity crossover.',
  ],
  [
    'name' => 'Wuthering Waves',
    'img' => 'assets/images/games/wuthering-waves.png',
    'img_fit' => 'cover',
    'genre' => 'Action RPG',
    'badge' => 'Best Ongoing',
    'featured' => false,
    'new_this_month' => false,
    'published_month' => '2026-03',
    'platforms' => ['Android Tablet'],
    'best_tablet' => 'Galaxy Tab S10 Ultra',
    'fit' => 'A stronger tablet gives the combat, exploration, and visual effects enough screen and performance headroom to land properly.',
    'best_for' => 'Players who want a big live-service action RPG and do not mind an ongoing grind.',
    'source_label' => 'Google Play Best Ongoing 2025',
    'source_url' => 'https://blog.google/products/google-play/best-apps-games-2025/',
    'shop_href' => 'shop.php?brand=Samsung',
    'tablet_brand' => 'Samsung',
    'cta_label' => 'Shop Galaxy Tab Picks',
    'review_href' => 'reviews.php',
    'comparison_note' => 'A good conversion path for readers who want the biggest Android screen and flagship-level gaming headroom.',
  ],
  [
    'name' => 'Chants of Sennaar',
    'img' => 'assets/images/games/chants-of-sennaar.png',
    'img_fit' => 'cover',
    'genre' => 'Puzzle Adventure',
    'badge' => 'Best Indie',
    'featured' => false,
    'new_this_month' => true,
    'published_month' => '2026-04',
    'platforms' => ['Android Tablet'],
    'best_tablet' => 'Galaxy Tab S9 FE',
    'fit' => 'Its visual-language puzzles and cleaner pace work especially well on a screen that gives the art and symbols more room.',
    'best_for' => 'Players who want something thoughtful, stylish, and different from the usual mobile chart leaders.',
    'source_label' => 'Google Play Best Indie 2025',
    'source_url' => 'https://blog.google/products/google-play/best-apps-games-2025/',
    'shop_href' => 'shop.php?brand=Samsung',
    'tablet_brand' => 'Samsung',
    'cta_label' => 'Shop Value Android Tablets',
    'review_href' => 'reviews.php',
    'comparison_note' => 'Useful for value-minded shoppers deciding whether a midrange Android tablet is enough for puzzle and indie play.',
  ],
];

$playStyles = [
  [
    'title' => 'Best for quick sessions',
    'game' => 'Pokemon TCG Pocket',
    'desc' => 'Short rounds, strong touch flow, and a layout that works whether you are on the couch or waiting in line.',
  ],
  [
    'title' => 'Best premium single-player pick',
    'game' => 'DREDGE',
    'desc' => 'A more console-like tablet experience with mood, pacing, and actual atmosphere.',
  ],
  [
    'title' => 'Best racing game',
    'game' => 'Disney Speedstorm',
    'desc' => 'High energy, clear visuals, and official recognition for strong multi-device play.',
  ],
  [
    'title' => 'Best story-heavy game',
    'game' => 'Disco Elysium',
    'desc' => 'The kind of game that gets easier to sink into when text and interface elements have real space.',
  ],
  [
    'title' => 'Best action RPG',
    'game' => 'Wuthering Waves',
    'desc' => 'A big-screen Android pick when you want movement, combat, and a live-service progression loop.',
  ],
  [
    'title' => 'Best visual showcase',
    'game' => 'Infinity Nikki',
    'desc' => 'A strong fit for high-end iPads that can turn style and environment detail into the point of the experience.',
  ],
];

$tabletMatches = [
  [
    'tablet' => 'iPad Gaming Picks',
    'games' => 'DREDGE, Infinity Nikki, and Prince of Persia Lost Crown',
    'desc' => 'Best for players who want polished premium releases and the strongest tablet-first ecosystem.',
    'shop_href' => 'shop.php?brand=Apple',
  ],
  [
    'tablet' => 'Galaxy Tab Gaming Picks',
    'games' => 'Disney Speedstorm, Wuthering Waves, and Pokemon TCG Pocket',
    'desc' => 'Best for players who want large Android displays, multitasking flexibility, and a mix of action and pick-up-and-play titles.',
    'shop_href' => 'shop.php?brand=Samsung',
  ],
  [
    'tablet' => 'Surface Gaming Picks',
    'games' => 'Disney Speedstorm and Disco Elysium',
    'desc' => 'Best for users who split time between work and games and want a tablet that still behaves like a PC when needed.',
    'shop_href' => 'shop.php?brand=Microsoft',
  ],
  [
    'tablet' => 'Budget Tablet Gaming Picks',
    'games' => 'Pokemon TCG Pocket and lighter casual titles',
    'desc' => 'Best for buyers who want card, puzzle, and family-friendly play without flagship-tablet pricing.',
    'shop_href' => 'shop.php?brand=Amazon',
  ],
];

$sources = [
  [
    'label' => 'Apple App Store Awards 2025',
    'url' => 'https://developer.apple.com/app-store/app-store-awards-2025/',
  ],
  [
    'label' => 'Apple App Store Awards finalists',
    'url' => 'https://www.apple.com/gw/newsroom/2025/11/apple-announces-finalists-for-the-2025-app-store-awards/',
  ],
  [
    'label' => 'Google Play Best of 2025',
    'url' => 'https://blog.google/products/google-play/best-apps-games-2025/',
  ],
];

$monthlyUpdates = [
  [
    'title' => 'Refreshed card art across the lineup',
    'desc' => 'All eight game cards now carry artwork so the page reads like current editorial instead of a text-only landing page.',
  ],
  [
    'title' => 'Featured pick stays conversion-friendly',
    'desc' => 'Pokemon TCG Pocket remains in the hero because it is still the easiest recommendation to connect to both Apple and Android tablet buyers.',
  ],
  [
    'title' => 'Narrative and indie picks broaden the mix',
    'desc' => 'Disco Elysium and Chants of Sennaar strengthen the page for readers looking beyond the usual action and racing recommendations.',
  ],
];

$categoryGuides = [
  [
    'title' => 'Best iPad Games',
    'copy' => 'If the reader is shopping premium tablets, lead with DREDGE, Infinity Nikki, and Prince of Persia Lost Crown. These games help justify brighter displays, better speakers, and stronger sustained performance.',
    'shop_href' => 'shop.php?brand=Apple',
    'review_href' => 'reviews.php',
  ],
  [
    'title' => 'Best Android Tablet Games',
    'copy' => 'For Android buyers, keep Pokemon TCG Pocket, Wuthering Waves, Disney Speedstorm, and Chants of Sennaar in rotation. That mix gives you quick-play, live-service, multiplayer, and indie discovery angles on one page.',
    'shop_href' => 'shop.php?brand=Samsung',
    'review_href' => 'reviews.php',
  ],
  [
    'title' => 'Best Surface Games',
    'copy' => 'Surface should stay positioned as the work-and-play pick. Disney Speedstorm and Disco Elysium are useful because they support the story that a Surface can cover both light gaming and everyday PC needs.',
    'shop_href' => 'shop.php?brand=Microsoft',
    'review_href' => 'reviews.php',
  ],
];

$faqItems = [
  [
    'question' => 'What games are best on tablets right now?',
    'answer' => 'The best tablet games right now are the ones that use the extra screen well: Pokemon TCG Pocket for fast sessions, DREDGE for premium single-player play, Disney Speedstorm for multi-device racing, and Disco Elysium for story-heavy reading and choice-driven gameplay.',
  ],
  [
    'question' => 'Are iPads or Android tablets better for gaming?',
    'answer' => 'iPads are usually the better fit for premium releases and polished tablet-first ecosystems, while Android tablets give more flexibility across screen sizes and price points. The best choice depends on whether the reader wants premium single-player titles or broader value and multitasking.',
  ],
  [
    'question' => 'Which tablet should I buy for gaming and everyday use?',
    'answer' => 'A shopper who wants gaming plus everyday use should match the tablet to the games they actually play. Galaxy Tab models are strong for Android flexibility, iPads are strong for premium polish, and Surface devices work best when productivity matters as much as entertainment.',
  ],
  [
    'question' => 'Should I add a protection plan to a gaming tablet?',
    'answer' => 'If the tablet will travel often or be used by kids and families, a protection plan can make sense. Tablet Masters already has protection options on the plans page, so this page should keep linking shoppers from game picks into the right protection flow.',
  ],
];
